name: FooBarCI

env:
  PYTHON_RUN_ENV: test
  PYTHON_VERSION: 3.13

on:
  workflow_call:

jobs:
  run_script:
    name: Run script
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "${{ env.PYTHON_VERSION }}"
          cache: pip
      - name: Run python script
        run: |
          python main.py
          echo "And PYTHON_VERSION is: ${{ env.PYTHON_VERSION}}"
        shell: bash